// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one
insert into branches (
    id, created_at, updated_at, name, address, company_id
) values (
    $1, $2, $3, $4, $5, $6
) returning id, created_at, updated_at, name, address, company_id
`

type CreateBranchParams struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      string
	Address   string
	CompanyID pgtype.UUID
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Address,
		arg.CompanyID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Address,
		&i.CompanyID,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
delete from branches where id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const getBranchesByCompany = `-- name: GetBranchesByCompany :many
select
    id,
    created_at,
    updated_at,
    name,
    address
from branches
where company_id = $1
`

type GetBranchesByCompanyRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      string
	Address   string
}

func (q *Queries) GetBranchesByCompany(ctx context.Context, companyID pgtype.UUID) ([]GetBranchesByCompanyRow, error) {
	rows, err := q.db.Query(ctx, getBranchesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBranchesByCompanyRow
	for rows.Next() {
		var i GetBranchesByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
update branches set
    updated_at = $1,
    name = $2,
    address = $3
where id = $4
returning id, created_at, updated_at, name, address, company_id
`

type UpdateBranchParams struct {
	UpdatedAt pgtype.Timestamptz
	Name      string
	Address   string
	ID        pgtype.UUID
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.UpdatedAt,
		arg.Name,
		arg.Address,
		arg.ID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Address,
		&i.CompanyID,
	)
	return i, err
}
