// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWarehouse = `-- name: CreateWarehouse :one
insert into warehouses (
    id, created_at, updated_at, name
) values (
    $1, $2, $3, $4
) returning id, created_at, updated_at, name
`

type CreateWarehouseParams struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      string
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteWarehouse = `-- name: DeleteWarehouse :exec
delete from warehouses where id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWarehouse, id)
	return err
}

const getWarehouses = `-- name: GetWarehouses :many
select
    id,
    created_at,
    updated_at,
    name
from warehouses
`

func (q *Queries) GetWarehouses(ctx context.Context) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, getWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
update warehouses set
    updated_at = $1,
    name = $2
where id = $3
returning id, created_at, updated_at, name
`

type UpdateWarehouseParams struct {
	UpdatedAt pgtype.Timestamptz
	Name      string
	ID        pgtype.UUID
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse, arg.UpdatedAt, arg.Name, arg.ID)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
